2019-11-19 19:11:29,971 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-19 19:12:22,098 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-19 19:13:41,541 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-19 19:25:32,839 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-19 19:26:33,893 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 00:08:12,172 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 16:38:08,205 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 16:56:01,840 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:03:04,341 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:03:08,221 ERROR: Exception on /user/master [GET] [in /Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/noahcg/Desktop/microblog/app/routes.py", line 119, in user
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'page' is not defined
2019-11-20 17:03:47,410 ERROR: Exception on /user/master [GET] [in /Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/noahcg/Desktop/microblog/app/routes.py", line 119, in user
    posts = current_user.followed_posts().paginate(
NameError: name 'page' is not defined
2019-11-20 17:03:52,522 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:03:55,302 ERROR: Exception on /user/master [GET] [in /Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/noahcg/Desktop/microblog/app/routes.py", line 121, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/noahcg/Desktop/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/noahcg/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/noahcg/Desktop/microblog/app/templates/user.html", line 32, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2019-11-20 17:04:58,955 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:05:52,594 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:06:53,273 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:06:56,130 ERROR: Exception on /user/master [GET] [in /Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/noahcg/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/noahcg/Desktop/microblog/app/routes.py", line 122, in user
    next_url=next_url, prev_url=prev_url)
NameError: name 'next_url' is not defined
2019-11-20 17:07:15,502 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:11:01,571 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:12:15,422 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:12:38,157 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:13:27,388 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
2019-11-20 17:14:30,381 INFO: Microblog startup [in /Users/noahcg/Desktop/microblog/app/__init__.py:72]
